{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "ava.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ava.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.serviceMonitor.additionalLabels | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - honorLabels: true
    path: /metrics
    port: metrics
  selector:
    matchLabels:
      {{- include "ava.selectorLabels" . | nindent 6 }}
{{- end }}