FROM golang:1.23-alpine as builder

ARG REVISION

WORKDIR /ava

COPY go.mod .

COPY go.sum .

COPY ./prisma/schema.prisma ./schema.prisma

RUN go mod download

RUN go run github.com/steebchen/prisma-client-go prefetch

ENTRYPOINT [ "go", "run", "github.com/steebchen/prisma-client-go", "db", "push" ]